# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-07 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[(b'C', b'COMPLEATED'), (b'P', b'PANDING')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[(b'1', b'1\xef\xb8\x8f\xe2\x83\xa3'), (b'2', b'2\xef\xb8\x8f\xe2\x83\xa3'), (b'3', b'3\xef\xb8\x8f\xe2\x83\xa3'), (b'4', b'4\xef\xb8\x8f\xe2\x83\xa3'), (b'5', b'5\xef\xb8\x8f\xe2\x83\xa3'), (b'6', b'6\xef\xb8\x8f\xe2\x83\xa3'), (b'7', b'7\xef\xb8\x8f\xe2\x83\xa3'), (b'8', b'8\xef\xb8\x8f\xe2\x83\xa3'), (b'9', b'9\xef\xb8\x8f\xe2\x83\xa3'), (b'10', b'\xf0\x9f\x94\x9f')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
